---
apiVersion: v1
kind: ConfigMap
metadata:
  name: env-tz
data:
  TZ: Asia/Seoul
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  creationTimestamp: null
  name: mysql-creds
stringData:
  password: "passw0rd!@#"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: properties-file
data:
  was-properties: |
    spring.datasource.url=jdbc:mysql://petclinic-db-svc:3306/petclinic
    spring.datasource.username=root
    spring.datasource.password=passw0rd!@#
    logging.file.name=/log/application.log
    spring.flyway.baselineOnMigrate = true

